package com.yida.user.dao;

import com.yida.user.dataObject.UserInfoDO;

public interface UserInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Jun 28 17:21:26 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Jun 28 17:21:26 CST 2019
     */
    int insert(UserInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Jun 28 17:21:26 CST 2019
     */
    int insertSelective(UserInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Jun 28 17:21:26 CST 2019
     */
    UserInfoDO selectByPrimaryKey(String id);

    /**
     * 通过账号获取信息
     *
     * @return
     */
    UserInfoDO selectByAccount(String account);


    UserInfoDO selectByTelphone(String telphone);

    UserInfoDO selectByLoginNum(String loginNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Jun 28 17:21:26 CST 2019
     */
    int updateByPrimaryKeySelective(UserInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Jun 28 17:21:26 CST 2019
     */
    int updateByPrimaryKey(UserInfoDO record);
}